### ISSUE TITLE
Role does not conform to ansible-galaxy structure

### ISSUE THREAD

**Issue by danschmidt5189** [IQSS/dataverse-ansible#11]
Handled by #13. 

We integrate all third-party roles by way of an ansible-galaxy requirements.yml file, e.g.:

```yml
- src: git@github.com:IQSS/dataverse-ansible.git
  scm: git
  version: v1.2.3
```

That's not possible given the current structure of the role:

- The actual role is nested under `./roles`
- There's no `meta/main.yml`
