### ISSUE TITLE
support dataverse-sample-data

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#83]
I created a new repo at https://github.com/IQSS/dataverse-sample-data and would love it if dataverse-ansible supported it.

Hopefully the README has enough direction. Once you do all the set up, it's a matter of running this command:

    python create_sample_data.py

I know that a `sampledata` was already added to `main.yaml` as part of #37. Here's how it looks right now:

```
  sampledata:
    enabled: false
    sampledir: "{{ playbook_dir }}/sampledata"
    sampledatasets: "{{ playbook_dir }}/sampledata/datasets"
    sampledataverses: "{{ playbook_dir }}/sampledata/dataverses"
    sampleusers: "{{ playbook_dir }}/sampledata/users"
    samplefiles: "{{ playbook_dir }}/sampledata/files"
```

I'm not sure what to call the new one. Probably not `sampledata2`. 😄 I'm open to ideas.

The issue I'm working on in the main Dataverse issue tracker is https://github.com/IQSS/dataverse/issues/5235
