### ISSUE TITLE
Support for collectd and Grafana

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-ansible#99]
Now that pull request #96 has been merged, Prometheus is installed and running.

From discussion at http://irclog.iq.harvard.edu/dataverse/2019-08-22#i_102865 @pmauduit recommends adding collectd and Grafana next.

Over at http://irclog.iq.harvard.edu/dataverse/2019-08-23#i_103066 I suggested creating this issue so @pmauduit can leave comments in here to indicate whatever commands he ran on an EC2 instance I spun up to install and configure collectd and Grafana. Thanks!!!

**Comment by pmauduit** [comment]
It seems that a vanilla setup of prometheus will gather by default some metrics related to its own process and golang. My idea then is to setup collectd with the prometheus writer:

```
$ yum install collectd
# vim /etc/collectd.d/prometheus.conf
<Plugin "write_prometheus">
  Port "9090"
</Plugin>
```

And see if we can gather default metrics from collectd (memory usage, %CPU, at least it is the default ones we have under debian-like distros, I expect centos to provide the same).

**Comment by pmauduit** [comment]
Unfortunately, I stumble upon this issue:
https://github.com/collectd/collectd/issues/2715

**Comment by pmauduit** [comment]
> Unfortunately, I stumble upon this issue:
> [collectd/collectd#2715](https://github.com/collectd/collectd/issues/2715)

Workaround discussed on IRC:

```
$ setenforce Permissive
```

**Comment by pmauduit** [comment]
Proometheus configuration to scrape Collectd:

```
[...]
scrape_configs:
  - job_name: 'dataverse'
    static_configs:
    - targets: ['localhost:9090']
- job_name: collectd
  static_configs:
  - targets: ['localhost:9103']
```
